#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This script imports test vectors from the X-Wing draft.  To use:
#
#    wget https://www.ietf.org/archive/id/draft-connolly-cfrg-xwing-kem-10.txt
#    $PATH_TO_THIS_SCRIPT draft-connolly-cfrg-xwing-kem-10.txt > lib/crypto/tests/xwing-testvecs.h

import hashlib
import os
import sys

SCRIPT_NAME = os.path.basename(__file__)
FIELD_NAMES = set(["seed", "sk", "pk", "eseed", "ct", "ss"])
FIRST_FIELD = "seed"

XWING_SEED_BYTES = 32
XWING_PUBLIC_KEY_BYTES = 1216
XWING_SECRET_KEY_BYTES = 32
XWING_ESEED_BYTES = 64
XWING_CIPHERTEXT_BYTES = 1120
XWING_SHARED_SECRET_BYTES = 32


def check_length(val, expected_len):
    assert len(val) == expected_len
    return val


class Testvec:
    def __init__(self, tv):
        self.seed = check_length(tv["seed"], XWING_SEED_BYTES)
        self.pk = check_length(tv["pk"], XWING_PUBLIC_KEY_BYTES)
        self.sk = check_length(tv["sk"], XWING_SECRET_KEY_BYTES)
        self.eseed = check_length(tv["eseed"], XWING_ESEED_BYTES)
        self.ct = check_length(tv["ct"], XWING_CIPHERTEXT_BYTES)
        self.ss = check_length(tv["ss"], XWING_SHARED_SECRET_BYTES)


def load_testvecs(file):
    testvecs = []
    with open(file) as file:
        in_appendix = False
        tv = None
        cur_field = None
        for line in file:
            if line.startswith("Appendix C."):
                in_appendix = True
            elif line.startswith("Appendix D."):
                break
            fields = line.split()
            if len(fields) == 0 or not in_appendix:
                continue
            if fields[0].strip() in FIELD_NAMES:
                cur_field = fields[0].strip()
                if cur_field == FIRST_FIELD:
                    if tv:
                        testvecs.append(Testvec(tv))
                    tv = {}
                tv[cur_field] = b""
                if len(fields) == 1:
                    continue
                possible_data = fields[1].strip()
            elif not cur_field:
                continue
            else:
                possible_data = fields[0].strip()
            try:
                data = bytes.fromhex(possible_data)
                tv[cur_field] += data
            except ValueError:
                pass
        testvecs.append(Testvec(tv))
    return testvecs


def print_bytes(prefix, value, bytes_per_line):
    for i in range(0, len(value), bytes_per_line):
        line = prefix + "".join(f"0x{b:02x}, " for b in value[i : i + bytes_per_line])
        print(f"{line.rstrip()}")


def print_c_struct_u8_array_field(name, value):
    print(f"\t\t.{name} = {{")
    print_bytes("\t\t\t", value, 8)
    print("\t\t},")


testvecs = load_testvecs(sys.argv[1])

print(f"""/* SPDX-License-Identifier: GPL-2.0-or-later */
/* This file was generated by {SCRIPT_NAME} */

static const struct xwing_testvec {{
\tu8 seed[XWING_SEED_BYTES];
\tu8 pk_hash[SHA3_256_DIGEST_SIZE];
\tu8 sk_hash[SHA3_256_DIGEST_SIZE];
\tu8 eseed[XWING_ESEED_BYTES];
\tu8 ct_hash[SHA3_256_DIGEST_SIZE];
\tu8 ss[XWING_SHARED_SECRET_BYTES];
}} xwing_testvecs[] = {{""")
for tv in testvecs:
    print("\t{")
    print_c_struct_u8_array_field("seed", tv.seed)
    print_c_struct_u8_array_field("pk_hash", hashlib.sha3_256(tv.pk).digest())
    print_c_struct_u8_array_field("sk_hash", hashlib.sha3_256(tv.sk).digest())
    print_c_struct_u8_array_field("eseed", tv.eseed)
    print_c_struct_u8_array_field("ct_hash", hashlib.sha3_256(tv.ct).digest())
    print_c_struct_u8_array_field("ss", tv.ss)
    print("\t},")
print("};")
