#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
#
# This script imports test vectors from the Kyber reference code.  To use:
#
#   git clone https://github.com/pq-crystals/kyber
#   cd kyber/ref
#   make
#   ./test/test_vectors768 > ./test/tvecs768
#   ./test/test_vectors1024 > ./test/tvecs1024
#   $PATH_TO_THIS_SCRIPT ./test/
#
# This script generates the following files:
#
#   lib/crypto/tests/mlkem-testvecs.h
#   lib/crypto/fips-mlkem.h

import hashlib
import os
import sys

SCRIPT_NAME = os.path.basename(__file__)
LINUX_DIR = os.path.dirname(os.path.realpath(__file__)) + "/../.."

MLKEM_LENGTHS = {
    768: {
        "pk_len": 1184,
        "sk_len": 2400,
        "ct_len": 1088,
    },
    1024: {
        "pk_len": 1568,
        "sk_len": 3168,
        "ct_len": 1568,
    },
}

MLKEM_SEED_BYTES = 64
MLKEM_ESEED_BYTES = 32


def print_header(file):
    print("/* SPDX-License-Identifier: GPL-2.0-or-later */", file=file)
    print(f"/* This file was generated by {SCRIPT_NAME} */", file=file)
    print(f"/* clang-format off */", file=file)


def hex_to_bytes(hex_string, expected_bin_len):
    res = bytes.fromhex(hex_string)
    assert len(res) == expected_bin_len
    return res


def print_bytes(file, prefix, value, bytes_per_line):
    for i in range(0, len(value), bytes_per_line):
        line = prefix + "".join(f"0x{b:02x}, " for b in value[i : i + bytes_per_line])
        print(f"{line.rstrip()}", file=file)


def print_static_u8_array_definition(file, name, value):
    print("", file=file)
    print(f"static const u8 {name} = {{", file=file)
    print_bytes(file, "\t", value, 12)
    print("};", file=file)


class Testvec:
    def __init__(self, dict, paramset):
        lens = MLKEM_LENGTHS[paramset]
        self.pk = hex_to_bytes(dict["Public Key"], lens["pk_len"])
        self.sk = hex_to_bytes(dict["Secret Key"], lens["sk_len"])
        self.ct = hex_to_bytes(dict["Ciphertext"], lens["ct_len"])
        assert dict["Shared Secret A"] == dict["Shared Secret B"]
        self.ss = hex_to_bytes(dict["Shared Secret A"], 32)
        self.ss_rejected = hex_to_bytes(dict["Pseudorandom shared Secret A"], 32)


def load_testvecs(tvecs_file, paramset):
    testvecs = []
    cur = None
    with open(tvecs_file) as f:
        for line in f:
            (name, value) = line.split(":")
            if name == "Public Key":
                if cur:
                    testvecs.append(Testvec(cur, paramset))
                cur = {}
            cur[name] = value.strip()
    if cur:
        testvecs.append(Testvec(cur, paramset))
    return testvecs


def hash_testvecs(testvecs):
    h = hashlib.shake_128()
    for tv in testvecs:
        h.update(tv.pk)
        h.update(tv.sk)
        h.update(tv.ct)
        h.update(tv.ss)  # From encapsulation
        h.update(tv.ss)  # From decapsulation
        h.update(tv.ss_rejected)
    return h.digest(length=32)


def gen_fips_file(tv):
    with open(LINUX_DIR + "/lib/crypto/fips-mlkem.h", "w") as file:
        ct_len = MLKEM_LENGTHS[768]["ct_len"]
        print_header(file)
        attribs = " __initconst __maybe_unused"

        # The test vectors were generated deterministically using the SHAKE128
        # of an empty string as the randomness.  Take the first MLKEM_SEED_BYTES
        # + MLKEM_ESEED_BYTES to get the seeds used by the first test vector.
        # Take an additional ct_len bytes to get the invalid ciphertext.
        rnd_data = hashlib.shake_128().digest(
            MLKEM_SEED_BYTES + MLKEM_ESEED_BYTES + ct_len
        )

        print_static_u8_array_definition(
            file,
            f"fips_test_mlkem768_seed[MLKEM_SEED_BYTES]{attribs}",
            rnd_data[:MLKEM_SEED_BYTES],
        )
        print_static_u8_array_definition(
            file,
            f"fips_test_mlkem768_eseed[MLKEM_ESEED_BYTES]{attribs}",
            rnd_data[MLKEM_SEED_BYTES : MLKEM_SEED_BYTES + MLKEM_ESEED_BYTES],
        )
        print_static_u8_array_definition(
            file,
            f"fips_test_mlkem768_pk[MLKEM768_PUBLIC_KEY_BYTES]{attribs}",
            tv.pk,
        )
        print_static_u8_array_definition(
            file,
            f"fips_test_mlkem768_sk[MLKEM768_SECRET_KEY_BYTES]{attribs}",
            tv.sk,
        )
        print_static_u8_array_definition(
            file,
            f"fips_test_mlkem768_ct[MLKEM768_CIPHERTEXT_BYTES]{attribs}",
            tv.ct,
        )
        print_static_u8_array_definition(
            file,
            f"fips_test_mlkem768_ss[MLKEM_SHARED_SECRET_BYTES]{attribs}",
            tv.ss,
        )
        print_static_u8_array_definition(
            file,
            f"fips_test_mlkem768_ct_invalid[MLKEM768_CIPHERTEXT_BYTES]{attribs}",
            rnd_data[MLKEM_SEED_BYTES + MLKEM_ESEED_BYTES :],
        )
        print_static_u8_array_definition(
            file,
            f"fips_test_mlkem768_ss_rejected[MLKEM_SHARED_SECRET_BYTES]{attribs}",
            tv.ss_rejected,
        )


if len(sys.argv) != 2:
    sys.stderr.write(f"Usage: {SCRIPT_NAME} TESTVECS_DIR\n")
    sys.exit(2)
testvecs_dir = sys.argv[1]

with open(LINUX_DIR + "/lib/crypto/tests/mlkem-testvecs.h", "w") as file:
    print_header(file)
    for paramset in [768, 1024]:
        testvecs = load_testvecs(testvecs_dir + f"/tvecs{paramset}", paramset)
        # There are 10000 test vectors, which take a bit long for a KUnit test.
        # Trim them down to just the first 1000.
        num_testvecs = min(len(testvecs), 1000)
        testvecs = testvecs[:num_testvecs]
        hash = hash_testvecs(testvecs)
        print(f"\n#define MLKEM{paramset}_NUM_TESTVECS {num_testvecs}", file=file)
        print_static_u8_array_definition(file, f"mlkem{paramset}_hash[32]", hash)
        if paramset == 768:  # FIPS only requires tests for one parameter set
            gen_fips_file(testvecs[0])
