#!/bin/bash

set -e -u -o pipefail

cd ~/linux
export ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-
make defconfig
cat >> .config << EOF
# CONFIG_MODULES is not set
CONFIG_BLK_INLINE_ENCRYPTION=y
CONFIG_MMC_CRYPTO=y
CONFIG_SCSI_UFS_CRYPTO=y
CONFIG_FS_ENCRYPTION=y
CONFIG_FS_ENCRYPTION_INLINE_CRYPT=y
CONFIG_CRYPTO_ADIANTUM=y
CONFIG_CRYPTO_HCTR2=y
CONFIG_CRYPTO_ESSIV=y
CONFIG_F2FS_FS=y
CONFIG_FS_VERITY=y
# CONFIG_CRYPTO_DEV_QCE is not set
EOF
#cat ~/kconfigs/crypto >> .config
make olddefconfig
make -j$(nproc) Image.gz dtbs
mkbootimg --kernel arch/arm64/boot/Image.gz \
	  --dtb arch/arm64/boot/dts/qcom/sm8650-hdk.dtb \
	  --os_version 15.0.0 \
	  --os_patch_level 2025-01 \
	  --cmdline "earlycon console=ttyMSM0 root=PARTLABEL=userdata rw qcom_ice.use_wrapped_keys=1" \
	  --header_version 2 \
	  --output boot.img
fastboot erase boot
fastboot boot boot.img
